### ISSUE TITLE
AEDAT splitter's parameters

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/pyNAVIS#1]
Is it necessary to indicate a range when splitting an AEDAT? I mean, I would like to remove a small part from the beginning of the document, so I would like to do something like: split(300, the_end_of_the_aedat_file), where the range 0-299 should be removed.

Thanks in advance! :)

**Comment by jpdominguez** [comment]
Solved in [this commit](https://github.com/jpdominguez/pyNAVIS/commit/1c5ee5dbcdeb58884c8dc930e3b56568509b8929). Thanks!
