### ISSUE TITLE
Function "Functions.PDF_report" does not close any Figure

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/pyNAVIS#11]
When generating multiple PDF reports (e.g., PDF reports from a dataset), all the figures are kept open. This leads that the computer runs slow and slow... Or even a memory problem.

Inside the function `Functions.PDF_report`, at the end, when the `pdf.close()` is called, maybe it could be good to call also to `plt.close('all')` in order to close all the generated and showed figures.

**Comment by jpdominguez** [comment]
Fixed in [the latest push](https://github.com/jpdominguez/pyNAVIS/commit/c774acb7fd13244934670734952395bbd004ca8d)!
