### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Moshrefi** [jpdominguez/pyNAVIS#18]
When running the script for 130Hz_mono_64ch_ONOFF_addr2b_ts02.aedat, an issue occurred due to a condition check.

**Problem**:
The condition `spikes_file.timestamps != []` was causing the problem.

**Resolution**:
Changed the condition to `len(spikes_file.timestamps) > 0`, which resolved the issue.

Affected Files:

    functions.py
    objects.py

**Comment by jpdominguez** [comment]
Thank you very much for pointing this issue. This is due to previous migration from lists to numpy arrays. It's already been fixed merging your pull request into the main branch.
