### ISSUE TITLE
Use data.log file format as allowed input file

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/pyNAVIS#2]
In order to use the pyNAVIS within the python code from YCM library (YARP project - IIT), it would be good to provide to the pyNAVIS software a data.log file with a specific format instead of a .aedat file. The format would be:

Example of a single line:
0.003041,0,1,0,0,23,0

Each field, separated by a comma, means:
ts, auditory_model, channel, xso_type, neuron_id, freq_ch, pol

Where:
-     pol = polarity (0 --> pos; 1 --> neg), 
-     freq_ch = frequency channel(from 0 to 31),
-     neuron_id = neuron ID from ITD network(from 0 to 15),
-     xso_type = olive model (0 --> MSO; 1 --> LSO),
-     channel = left or right cochlea (0 --> left; 1 --> right)
-     auditory_model = spikes coming from NAS or SOC (0 --> NAS; 1 --> SOC),
-     ts = timestamps (in seconds)

**Comment by jpdominguez** [comment]
This enhancement has been included in this commit[https://github.com/jpdominguez/pyNAVIS/commit/edde33b9382937da733b7739864073b30ce08605]
