### ISSUE TITLE
Implementation of a function to calculate the Interspike Interval

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/pyNAVIS#5]
It would be nice to have a function that calculates the Interspike Interval (ISI) of a list of timestamps. The ISI of the spike-pair i_th can be defined as:

`ISI ( i ) = ts ( i + 1) - ts ( i )`

where _ts_ is the timestamp.

Note that if the timestamp list contains X elements, the ISI list will contain X-1 elements. An implementation example could be:

```python
# For each pair of timestamps (i+1, i), calculate the ISI
for index in range (0, num_extracted_events-1):
    isi_values.append(channel_extracted_data.timestamps[index+1] - channel_extracted_data.timestamps[index])
```

**Comment by jpdominguez** [comment]
Added in [the last push](https://github.com/jpdominguez/pyNAVIS/commit/d5f6917a356b29f482388fc361c4952950f35e43)!
