### ISSUE TITLE
Time unit not indicated in Functions.mono_to_stereo(..., delay, ...)

### ISSUE THREAD

**Issue by dgutierrezATC** [jpdominguez/pyNAVIS#7]
In the function Functions.mono_to_stereo(), the parameter "delay" allows you to add some delay between the left and the right cochlear. However, not time unit is indicated, so it's not possible to know if you are adding some microseconds, milliseconds or nanoseconds.

**Comment by dgutierrezATC** [comment]
In addition, it would be nice to clarify the sentence 

> Delay introduced from the left and right spikes. Can be either negative or positive.

It's hard to understand if the delay is added just to the left, to the right, to both... One idea could be:

"The timestamp of the left event (ts_left) is the reference. So the timestamp of the right event (ts_right) will be ts_right = ts_left + delay". Therefore, if the delay is positive, the value is added to the ts_left value, and if the delay is negative, it will be subtracted.

**Comment by jpdominguez** [comment]
Solved in the next  commit to master.
